### PR TITLE
Convert module to use PDK 2.1.1

### PR DESCRIPTION
**Pull request by Phil-Friderici**
Had to slightly change the `sudo_version.rb` fact to satisfy rubocop. Guessing that this change will have no impact, but two pairs of eyes are better than just one ;)

Local PDK validation and unit tests were successfully for Puppet 5.5.22, 6.22.1, and 7.7.0.

### CODE REVIEW

**Comment by Phil-Friderici** [comment]
The unit tests are **very old** and should become reworked completely at a later time.

**Comment by Phil-Friderici** [comment]
Need to check if `sudo_version.rb` still works as intended on an internal machine. Could someone help please ?

**Comment by anders-larsson** [comment]
Gave your changes a try and it seems to be working correctly.

```...
Info: Retrieving plugin

Notice: /File[/opt/puppetlabs/puppet/cache/lib/facter/sudo_version.rb]/content:
--- /opt/puppetlabs/puppet/cache/lib/facter/sudo_version.rb     2021-04-21 11:47:52.820672697 +0200
+++ /tmp/puppet-file20210727-392244-1lsypf6     2021-07-27 13:19:05.051486723 +0200
@@ -8,11 +8,11 @@
     begin
       path = `which sudo`.strip

-      if path.length == 0 or not File.exists?(path)
+      if path.empty? || !File.exist?(path)
         raise 'path does not exist'
       end

-      regexp = /^Sudo version +(\S+)$/
+      regexp = %r{^Sudo version +(\S+)$}

       result = `#{path} -V`.strip


Notice: /File[/opt/puppetlabs/puppet/cache/lib/facter/sudo_version.rb]/content: content changed '{sha256}01c76561902c186d7eec2a2246bf0583abc875f39ca6cff32167befeeac13117' to '{sha256}f9d21adf6ae2343421faef4f8c6daa115d520609a1911b18b413f172cc98f2d8'
Info: Loading facts
...

# facter -p sudo_version
1.8.29
```

**Comment by Phil-Friderici** [comment]
@anders-larsson Do you think we are ready to merge then ?

**Review by anders-larsson — APPROVED** [review]
Looks good to me!

**Pull request merged**
